### ISSUE TITLE
Typo in 5.1 DG

### ISSUE THREAD

**Issue by zlimez** [zlimez/pe#10]
"Should the `TASK_NUMBER` entered is out of bound" could probably be reworded as "If the `TASK_NUMBER` entered is out of bounds".

![Screenshot 2022-11-11 at 5.37.53 PM.png](https://raw.githubusercontent.com/zlimez/pe/main/files/012738b4-8ed5-42e6-902c-08dff187cfce.png)

**Comment by nus-se-script** [comment]
Your response not required for this bug as the team has accepted the bug as it is.
